name: 2345王牌联盟
 
on:
  workflow_dispatch:
  schedule:
     - cron: '1/20 10-23/3 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install and 运行 2345王牌联盟
        env:
          WPLM_COOKIE: ${{ secrets.WPLM_COOKIE }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        run: |
          npm install
          node Task/jf2345.js

 